# Change these first
owner: deephdc # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: DEEP web page
    url: https://deep-hybrid-datacloud.eu/
  - name: DEEP Training Dashboard
    url: https://train.deep-hybrid-datacloud.eu/
  - name: DEEPaaS
    url: https://deepaas.deep-hybrid-datacloud.eu/
  - name: DEEP Marketplace
    url: https://marketplace.deep-hybrid-datacloud.eu/
  - name: Identity and access Management (IAM)
    url: https://iam.deep-hybrid-datacloud.eu/
  - name: NextCloud
    url: https://nc.deep-hybrid-datacloud.eu/
  - name: PaaS dashboard
    url: https://deep-paas.cloud.ba.infn.it/
  - name: PaaS Orchestrator
    url: https://deep-paas.cloud.ba.infn.it/orchestrator
  - name: Configuration Management DB (CMDB) 	
    url: https://deep-paas.cloud.ba.infn.it/cmdb
  - name: Infrastructure Manager (IM)
    url: https://deep-paas.cloud.ba.infn.it/im
  - name: SLA Manager (SLAM) 	
    url: https://deep-slam.cloud.ba.infn.it:8443/rest/slam
  - name: Provider IFCA-LCG2   eu.indigo-datacloud.mesos
    url: https://mesos.cloud.ifca.es/mesos
  - name: Provider IFCA-LCG2   eu.indigo-datacloud.marathon
    url: https://mesos.cloud.ifca.es/marathon
  - name: Provider IFCA-LCG2   org.openstack.nova
    url: https://api.cloud.ifca.es:5000/v3
  - name: Provider IISAS-Bratislava    eu.indigo-datacloud.chronos
    url: https://mesos.ui.sav.sk/chronos
  - name: Provider IISAS-Bratislava    eu.indigo-datacloud.marathon
    url: https://mesos.ui.sav.sk/marathon
  - name: Provider QCG     eu.deep.qcg
    url: https://qcg-deep.apps.paas-dev.psnc.pl/api
  - name: Provider RECAS-BARI  org.openstack.nova
    url: https://cloud.recas.ba.infn.it:5000/v3

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.deep-hybrid-datacloud.eu
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DEEP Service status
  introTitle: "DEEP platform and service status"
  introMessage: This page provides a real time overview of the [DEEP-Hybrid-DataCloud](https://deep-hybrid-datacloud.eu/the-platform/) platform and service status.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
